[devdeployement]
BROKER_HOST = 172.29.169.30
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = deployement
QUEUE = devtodeployement
#EXCHANGE_TYPE = fanout
AUTO_DELETE = true

[deployementQA-API]
BROKER_HOST = 172.29.169.30
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = deployementFanQA
QUEUE = deployementToQA-API
EXCHANGE_TYPE = fanout
AUTO_DELETE = true

[deployementQA-DB]
BROKER_HOST = 172.29.169.30
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = deployementFanQA
QUEUE = deployementToQA-DB
EXCHANGE_TYPE = fanout
AUTO_DELETE = true

[deployementQA-WEB]
BROKER_HOST = 172.29.169.30
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = deployementFanQA
QUEUE = deployementToQA-WEB
EXCHANGE_TYPE = fanout
AUTO_DELETE = true


[deployementPROD-API]
BROKER_HOST = 172.29.169.30
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = deployementFanPROD
QUEUE = deployementToPROD-API
EXCHANGE_TYPE = fanout
AUTO_DELETE = true

[deployementPROD-DB]
BROKER_HOST = 172.29.169.30
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = deployementFanPROD
QUEUE = deployementToPROD-DB
EXCHANGE_TYPE = fanout
AUTO_DELETE = true

[deployementPROD-WEB]
BROKER_HOST = 172.29.169.30
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = deployementFanPROD
QUEUE = deployementToPROD-WEB
EXCHANGE_TYPE = fanout
AUTO_DELETE = true
